name: reactive_file_picker
description: Wrapper around file_picker to use with reactive_forms.
version: 4.0.1
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_file_picker
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  reactive_forms: ">=16.0.0 <19.0.0"
  file_picker: ^10.1.2
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0
