name: reactive_image_picker
description: Wrapper around image_picker to work with reactive_forms
version: 8.0.1
repository: https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_image_picker
issue_tracker: https://github.com/artflutter/reactive_forms_widgets/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: ">=16.0.0 <19.0.0"
  freezed_annotation: ^3.0.0
  image_picker: ^1.1.2
  app_settings: ^6.1.1
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0